Repository adhiiimf/wisata-haruman-web, pull requests merged in 2023-05, with the labels that each got.

#5 DB Relationship V1
  app/Http/Controllers/ArticleController.php
  app/Http/Controllers/ProductController.php
  app/Http/Controllers/TravelController.php
  app/Models/Article.php
  app/Models/Product.php
  app/Models/Travel.php
  app/Traits/Uuid.php
  database/migrations/2023_05_01_201702_create_products_table.php
  database/migrations/2023_05_01_201840_create_travel_table.php
  database/migrations/2023_05_01_201906_create_articles_table.php
Labels: documentation, enhancement, backend

#7 Add Summernote Feature for Article Content Maker
  .gitignore
  app/Http/Controllers/ArticleController.php
  database/migrations/2023_05_02_115823_article_column_update.php
  resources/views/pages/admin/CreateArticle.blade.php
  resources/views/pages/admin/CreateProduct.blade.php
  routes/web.php
Labels: documentation, enhancement, frontend, backend

#10 Update Readme of this Repository
  README.md
Labels: documentation

#11 add wisata haruman logo v1
  public/assets/wisataharuman-logo.png
Labels: documentation

#16 POST Travel Destination Feature
  app/Http/Controllers/TravelController.php
  app/Models/Travel.php
  database/migrations/2023_05_04_110127_travel_table_update.php
  resources/views/pages/admin/CreateTravel.blade.php
  routes/web.php
Labels: documentation, enhancement, backend

#18 fix #2 Add dashboard, login, and signup page styles
  public/assets/garden-1.jpeg
  resources/views/Main.blade.php
  resources/views/auth/admin/Login.blade.php
  resources/views/auth/admin/Signup.blade.php
Labels: frontend

#19 Add View and Delete Feature for Product Content (admin-side)
  .gitignore
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/ProductController.php
  database/migrations/2023_05_11_124002_update_product_description.php
  public/assets/logo-color.png
  public/assets/whatsapp.svg
  resources/views/auth/admin/Login.blade.php
  resources/views/auth/admin/Signup.blade.php
  resources/views/components/NavAdmin.blade.php
  resources/views/pages/admin/CreateProduct.blade.php
  resources/views/pages/admin/DeleteProduct.blade.php
  resources/views/pages/admin/Product.blade.php
  resources/views/pages/admin/ViewProduct.blade.php
  routes/web.php
Labels: enhancement, frontend, backend

#23 Update Gradient Color for Landing Page
  resources/views/Main.blade.php
Labels: frontend

#31 Add Product data for lp
  app/Http/Controllers/MainController.php
  resources/views/Main.blade.php
  routes/web.php
Labels: frontend, backend
